### PR TITLE
Mumble Positional Audio Integration

### PR DESCRIPTION
**Pull request by jordanvr**
Hi,

I've adapted the positional audio link plugin Mumble provide into sm64 coop dx. The mumble connection relies on sharing memory so I figured it would be more appropriate to integrate it into the project proper rather than as a mod.

the plugin details can be found here: https://www.mumble.info/documentation/developer/positional-audio/link-plugin/

image

I've tested it on Windows and OSX, and verified that the audio positioning works as expected by testing with two players connected to mumble. 

Let me know if there is anything else you need for the PR, otherwise happy to see it become part of the project!

### CODE REVIEW

**Comment by EmeraldLoc** [comment]
Looks cool! Wanted to lyk you should merge into the `dev` branch rather then `main`.

**Comment by AgentXLP** [comment]
How does mumble hook into this? Does it read the memory of the process?

**Comment by jordanvr** [comment]
> How does mumble hook into this? Does it read the memory of the process?

This technique uses [Named Shared Memory](https://learn.microsoft.com/en-us/windows/win32/memory/creating-named-shared-memory), so yes Mumble reads this defined section of memory, but it as it is shared there are not the normal issues around reading the memory of a another process.

There is another technique that Mumble plugins can use that involves identifying the offsets of position data in ram and using those, which does straight up read the memory of a game's process.

**Comment by jordanvr** [comment]
I've just added an improvement around how the context is handled around rooms. I've left a comment in the code, but essentially the current room is not necessarily a room and shouldn't be used for context changes.

**Pull request merged**
