### PR TITLE
Display native language name in languages menu

### PR DESCRIPTION
**Pull request by tulpenkiste**
Small QoL feature that displays the native language name within the language menu for those that don't know the English name for their language.

Draft as the implementation could be better.

Screenshots:
image
image

### CODE REVIEW

**Comment by Agent-11** [comment]
This is indeed abysmal.

**Comment by tulpenkiste** [comment]
Ok, improved it to be less abysmal (no more lots of else ifs), I think its good for review now.

**Comment by Agent-11** [comment]
This is still not a good implementation imo... Not to mention the variable name `language_hell`.

**Comment by tulpenkiste** [comment]
> This is still not a good implementation imo... Not to mention the variable name `language_hell`.

Yeah, I agree. It definitely needs some work. I'm going to re-draft this while I think of a better system for this.

**Comment by AgentXLP** [comment]
Seems to have gone stale.

**Pull request closed without merging**
