### PR TITLE
added norender mode

### PR DESCRIPTION
**Pull request by iZePlayzYT**

### CODE REVIEW

**Comment by iZePlayzYT** [comment]
Exactly. This helps a lot if you want to just host without wasting to much resources

**Comment by AgentXLP** [comment]
`make HEADLESS=1`?

**Comment by iZePlayzYT** [comment]
headless does not work with coopnet, also the performance mode does allow you to access the chat to enter commands and you can change stuff without restarting since you have full access to the Menu/UI

**Comment by AgentXLP** [comment]
I see

**Comment by AgentXLP** [comment]
There is probably a better name you can pick for this I imagine

**Comment by iZePlayzYT** [comment]
do you have any idea?

**Comment by Isaac0-dev** [comment]
better to improve the headless server than introduce this dodgy method of running the game

**Comment by iZePlayzYT** [comment]
@Isaac0-dev improving headless does not allow you to access the chat and the menus. this is way better than headless in many use-cases. also @AgentXLP approved it before.

**Comment by AgentXLP** [comment]
I approved it because the code looked fine, Isaac merges PRs as of now

**Comment by AgentXLP** [comment]
I do agree though that the method is a bit dodgy

**Comment by iZePlayzYT** [comment]
i thought about it once again and have to agree that the parameter is a bad solution. but the ingame setting would be perfect for many reasons and cant be replaced with headless in some use cases. for example: if somebody who is currently hosting a lobby decides to play something else they would are forced to shut down the lobby because his computer is low-end and keeping coopdx running would waste to much resources. instead of shutting the game down they could disable rendering while not ingame without closing the lobby

**Pull request closed without merging**
