### PR TITLE
Optimization of mtxf_lookat()

### PR DESCRIPTION
**Pull request by Multi-Volt**
Hello,

While reviewing the current implementation of `mtxf_lookat()` in `math_util.c`, I identified some areas for optimization. Specifically, I noticed redundant calculations in the cross product operations, as well as the absence of checks for very small or zero xz distances. Any testing for these changes would be appreciated, below are my results.

Before Changes:
Screenshot from 2024-10-17 23-05-42

After Changes:
Screenshot from 2024-10-17 21-22-44

### CODE REVIEW

**Comment by Cooliokid956** [comment]
isn't that [3][3] supposed to be 1? or does this cause no errors

**Comment by Multi-Volt** [comment]
> isn't that [3][3] supposed to be 1? or does this cause no errors 

Good find, I didn't notice that I lumped that together. In the build I never saw any differences but I went ahead and fixed it just in case.

**Comment by Multi-Volt** [comment]
> the result seems to be different from the original `mtxf_lookat` if `roll` is not 0. from what i remember, vanilla sm64 doesn't use roll much but accuracy is still important

I fixed my code, I ended up forgetting a single negative sign on the normalization for the xzdist! Now the calculations appear to match for any roll.

**Review by Isaac0-dev — APPROVED** [review]
well done this function indeed accurate and faster in my testing.

**Pull request merged**
