### PR TITLE
force render rooms, effectively disabling the room system

### PR DESCRIPTION
**Pull request by Dominicentek**
self explanatory

### CODE REVIEW

**Comment by Agent-11** [comment]
... Why?

**Comment by eros71-dev** [comment]
This will cause clipping issues with the castle inside, and possibly HMC, not sure about BBH but may not in that specific case
imagen

**Comment by Isaac0-dev** [comment]
don't change the level geos, better to just disable the functionality in `geo_switch_area` if the level is a vanilla level.
also @eros71-dev  your linked image doesn't work

**Comment by eros71-dev** [comment]
I guess GitHub didn't like me, it was supposed to load just fine according to the preview, but basically you can see part of the wall "pillars" next to the stairs in the center of the castle inside when entering the way to go to the basement.

**Comment by eros71-dev** [comment]
imagen

**Pull request closed without merging**
