### PR TITLE
Fix frame rate

### PR DESCRIPTION
**Pull request by PeachyPeachSM64**
Fix inconsistent and inaccurate frame rate.
Still loses a bit of accuracy at high frame rates and breaks above 600 FPS due to `WAPI.delay` using a delta time in milliseconds.

Comparison:
fps

### CODE REVIEW

**Comment by AgentXLP** [comment]
Wdym breaks above 600 fps?

**Comment by PeachyPeachSM64** [comment]
delay becomes 0 and the frame rate is no longer limited

**Comment by djoslin0** [comment]
this one was super tricky, good work for figuring it out

**Comment by Isaac0-dev** [comment]
it looks like sdl doesn't provide any ways to delay by microseconds, but would it be worth using other built in functions to delay by microseconds for more accuracy?

**Comment by djoslin0** [comment]
making a frame limiter work past ~244 fps seems excessive to me, at that point just run uncapped

**Comment by AgentXLP** [comment]
True

**Pull request merged**
