### PR TITLE
Added `FONT_SPECIAL`

### PR DESCRIPTION
**Pull request by xLuigiGamerx**
`FONT_SPECIAL` is based on the special characters for the controls found in dialogs. I made the nametags use it:
image

### CODE REVIEW

**Comment by AgentXLP** [comment]
I feel like this font makes nametags very long and the previous font worked fine.

**Comment by xLuigiGamerx** [comment]
> I feel like this font makes nametags very long and the previous font worked fine.
It's the same width as the normal characters, I could make the nametags smaller in scale if you want.

**Comment by flipflopbell** [comment]
this is nice, a bold font would be pretty cool to have

**Comment by AgentXLP** [comment]
Merge conflicts

**Comment by xLuigiGamerx** [comment]
> Merge conflicts

Merged

**Pull request merged**
