### PR TITLE
Fixed Spanish grammar

### PR DESCRIPTION
**Pull request by supahfox**
Some strings are bad grammatically

### CODE REVIEW

**Comment by supahfox** [comment]
For example: "expresiones de odio"  translates as "hate expressions" and not "hate speech"

**Comment by AgentXLP** [comment]
Retarget to the `dev` branch please

**Comment by supahfox** [comment]
done

**Comment by eros71-dev** [comment]
Yeah some lines are definitely better with this one, I'm only worried about the "Intensidad de vibración" string, while it does sound better, I'm not sure if it fits entirely without being cut off, if it does though then yeah it's all for the better.

**Comment by AgentXLP** [comment]
I think it'll fit

**Pull request merged**
