### PR TITLE
Japanese Support

### PR DESCRIPTION
**Pull request by jasherton**
Adds japanese language support and some changes for UTF-16.

Apologies for the messy commit history. This is my first time making a pull request so I didn't know I had to make another branch to request just these specific changes.

Fonts used: k8x12 (Large), 源真ゴシック (Monospace Bold)

### CODE REVIEW

**Comment by Flower35** [comment]
I would stick with having all the source code (and assets) filenames in ASCII. There is no need to save the file as `'lang/日本語.ini"` if it can be `"lang/Japanese.ini"`, and have contents encoded in UTF-8 (instead of UTF-16LE, although I think with how current`".gitattributes"` are set up, everything that is not a binary file, is in UTF-8).

**Comment by jasherton** [comment]
Ok, but then the name that gets displayed in the settings would be "Japanese" instead of "日本語" as it should be. Should there be a key in the ini file for an optional display name?

**Comment by AgentXLP** [comment]
Holy shit

**Comment by AgentXLP** [comment]
There can be a display name if you want

**Comment by Flower35** [comment]
> Ok, but then the name that gets displayed in the settings would be "Japanese" instead of "日本語" as it should be. Should there be a key in the ini file for an optional display name?

Well, all other languages are just displayed in English (while opening the language settings).

For convenience, we could handle separate display names (English + native), which would look more-or-less like:
```
Czech (Čeština)
Dutch (Nederlands)
English
French (Français)
German (Deutsch)
Italian (Italiano)
Japanese (日本語)
Polish (Polski)
Portuguese (Português)
Russian (Русский)
Spanish (Español)
```

**Comment by jasherton** [comment]
Does it look alright now?

**Comment by Flower35** [comment]
Sorry, just noticed more problems:
- Target branch (`coop-deluxe:main`) is wrong - it should be `coop-deluxe:dev`. This will likely cause some merge conflicts.
- Code style inconsistency: 4 spaces changed into single tabs, and stray tabs added to some lines in a few (unrelated to this PR) source code files.
- A good practice is to also include one blank newline at the end of every text file (it helps with comparing changes or making further modifications, where you can easily place your cursor in the text editor).

Note: these file-formatting rules aren't really applied, until the developer does so themselves, or has properly configured IDE:
https://github.com/coop-deluxe/sm64coopdx/blob/main/.clang-format

**Comment by jasherton** [comment]
Understood. Do I close this and open a new one based on dev branch then?

**Comment by AgentXLP** [comment]
I fixed it

**Comment by jasherton** [comment]
Is it good now?

**Comment by Flower35** [comment]
Nice, looks way better now!

Also good catch on the `text++;` bug in `convert_unicode_char_to_u64()`. I think this went unnoticed as most UTF-8 characters were stored on at most 2 bytes for all other languages.

**Comment by jasherton** [comment]
Not sure why that conflict is still present but I'm going to change things a bit.

**Comment by jasherton** [comment]
Now it supports way more kanji with separate image sheets. I think you'll have to resolve that conflict though.

**Comment by Amy54Desu** [comment]
there has to be a better way to handle the Japanese font

**Comment by Amy54Desu** [comment]
The translations are a little funky so I'm going to do a little adjustments to them

**Comment by AgentXLP** [comment]
Yeah ngl I preferred having the Japanese characters in the normal and aliased font sheets, and I can't even merge this anyway because it says there's a merge conflict for some reason.

**Comment by jasherton** [comment]
I'll revert the change and combine them into the base sheets again. I thought it would be better to separate them with how large the images become. No idea how to fix the conflict though.

**Comment by Amy54Desu** [comment]
if you are on something like GitHub Desktop it will show you the merge conflict

**Comment by jasherton** [comment]
How is this a conflict? Am I missing something?
chrome_1OPfBkLP8Z
chrome_nVSQ6UmFS4

**Comment by jasherton** [comment]
Nevermind I didn't realize I could edit the text on that page.

**Comment by jasherton** [comment]
I'm noticing an issue with the font rendering that only happens when the image sheets are large like they are now.
sm64coopdx_BpiznUstwG
sm64coopdx_kwI8H8zI19

**Comment by AgentXLP** [comment]
Weird, you can make them separate again if that fixes the issue

**Comment by jasherton** [comment]
It does

**Comment by jasherton** [comment]
Should I close this and make a new pr to make the commit history neater?

**Comment by Amy54Desu** [comment]
here are my tweaks, to the translation (change .txt to .ini), main ones being ホスト -> 部屋主 ロビー -> 部屋
[Japanese.txt](https://github.com/user-attachments/files/18278777/Japanese.txt)

**Review by AgentXLP — APPROVED** [review]
Looking good now

**Comment by 3UPPER** [comment]
Oh hey, nice translations! I improved translations. I'm native Japanese, so I guess I did well.
but I have a problem: I couldn't understand what are "AGGRESSION" and "PAN_LEVEL" and "DECELERATION" on camera settings.
If you tell me about these, I can add it. Thank you.
Oh, the file is here:[Japanese.txt](https://github.com/user-attachments/files/18319205/Japanese.txt)

**Comment by 3UPPER** [comment]
hey, thank you for adding my translations!
but I noticed that I messed up about titles so I fixed it.
(Like "CONNECTING…". These "Mario-Like" fonts doesn't have Japanese characters so they were displayed as "???")
[Japanese.txt](https://github.com/user-attachments/files/18388084/Japanese.txt)

**Comment by AgentXLP** [comment]
D:

**Comment by AgentXLP** [comment]
From now on, open a PR or issue to send your updated Japanese language

**Pull request merged**
