### PR TITLE
more detailed mod description & added chat colors codes

### PR DESCRIPTION
**Pull request by iZePlayzYT**

### CODE REVIEW

**Comment by EmeraldLoc** [comment]
For those wondering what it looks like

Screenshot 2024-11-22 at 6 21 49 PM

**Comment by iZePlayzYT** [comment]
The reason for this is, that you can differentiate the mods if you have multiple versions of a mod with the same names.

**Comment by iZePlayzYT** [comment]
update: 
image
w

**Comment by iZePlayzYT** [comment]
image

**Comment by iZePlayzYT** [comment]
> that's outside of the scope of this PR, move it to its own branch and PR 

I dont know how to easily do this without having to delete this branch, the PR and create 2 new branches and 2 New PRs. I hope its okay this time. Next time i will make sure to create different PRs

**Comment by AgentXLP** [comment]
🤦‍♂️

**Comment by iZePlayzYT** [comment]
> 🤦‍♂️ 

?

**Pull request closed without merging**
