### PR TITLE
Fix arm compilation for macOS

### PR DESCRIPTION
**Pull request by EmeraldLoc**
On the latest version of macOS, arm compilation was busted due to crash handler and libs. Credit to AbnormalPoof for doing the discord stuff.

Btw git did some weird stuff, it was spitting out this when I ran `git commit -a`

```
warning: in the working copy of 'lib/bass/arm/libbass.so', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'lib/bass/arm/libbass_fx.so', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'lib/bass/bass.dll', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'lib/bass/bass.dylib', CRLF will be replaced by LF the next time Git touches it
..... (for every lib file in the changed files section, gotta love line endings)
```

So... make sure to check everything works on windows :/

### CODE REVIEW

**Comment by Agent-11** [comment]
What's wrong with the crash handler?

**Comment by EmeraldLoc** [comment]
The error is
```
src/pc/crash_handler.c:744:45: error: use of undeclared identifier 'gDjuiRoot'
        if (id == (s64)gPcDebug.tags[14]) { gDjuiRoot = NULL; }
```
The main reason I disabled the crash handler was because I assumed that was what it was meant to be (due to the main coop repo having it off for macos), if that's not the case, I can fix the actual problem instead.

**Comment by Agent-11** [comment]
Ahh, I see.

**Comment by Agent-11** [comment]
Just deleted my dumb question, I saw that error before and should have connected the dots.

**Comment by Agent-11** [comment]
I don't know if I want to merge this commit and make you a contributor to this project. You watched the trailer and immediately made your own dark theme (but worse) PR for the sm64ex-coop dev repo, not to mention past gripes I've had with you but I don't know if you've improved since then.

**Comment by EmeraldLoc** [comment]
Great concern you have, and honestly I can't really say anything about it. The reason I made the pr was because I wanted that in the base repo, but yea definitely should have not made that pr. It's very simple to recreate the pr, all I did was change the arm libs to the ones in the main coop repo (as something happened to them that made the linker not like them (maybe line endings?)) and then just did the thing with the crash handler.

**Pull request closed without merging**
