### PR TITLE
added chat color codes like in minecraft (&1, &e, &r, etc.)

### PR DESCRIPTION
**Pull request by iZePlayzYT**

### CODE REVIEW

**Comment by kermeow** [comment]
This maybe is over-complicating things, especially when it's replacing all matches for those strings with the already existing colour codes.

Also correct me if I'm wrong but I don't think `#fff` is the right colour for reset.

**Comment by iZePlayzYT** [comment]
1) there has been previous discussion, the new PR is because i was asked to split both changes in seperate PRs: https://github.com/coop-deluxe/sm64coopdx/pull/508

2) its more simplifying it, because writing just &1 is way faster than \#xxx\ if you want to quickly highlight something in chat. regarding the &r in minecraft it would reset the color to fff and also resets any style formatting codes like &k &m &o &l which are not existing in coopdx yet so its just resetting the color to fff currently.
 
3) it looks like this image

**Comment by iZePlayzYT** [comment]
> This maybe is over-complicating things, especially when it's replacing all matches for those strings with the already existing colour codes.
> 
> Also correct me if I'm wrong but I don't think `#fff` is the right colour for reset.

wait did you mean that the text in chat without formatting is not exactly fff?

**Comment by AgentXLP** [comment]
Sorry but the color codes were already simplified and I don't think we need another system for them.

**Comment by iZePlayzYT** [comment]
-.-

**Pull request closed without merging**
