### PR TITLE
Arena Fire Flower redesign

### PR DESCRIPTION
**Pull request by stvene3004**
Replaced the current Fire Flower model with a new one. Not much else to say about this one.
goofy_ahh_flower
The preview in this one looks a bit bugged, but it's been fixed since.

### CODE REVIEW

**Comment by Bloxxel64** [comment]
honestly looks great

**Comment by Agent-11** [comment]
Are you fine with me putting your model file on the private repo and committing you as a co-author?

**Comment by stvene3004** [comment]
> Are you fine with me putting your model file on the private repo and committing you as a co-author?

Sure.

**Comment by Agent-11** [comment]
Alright

**Pull request closed without merging**
