### PR TITLE
Hopefully fix directx mouselock (#53)

### PR DESCRIPTION
**Pull request by uuphoria2**
in game camera (camera.c)
You can merge this to main branch if you want tho i only used this in some of my coding projects (most of them not on github) so im not sure if it works tho for me it worked atleast
Referring to problem (#53)

### CODE REVIEW

**Comment by uuphoria2** [comment]
mentioned the wrong one

**Comment by uuphoria2** [comment]
Got it in dev branch and corrected everything

**Comment by Agent-11** [comment]
This is completely wrong

**Comment by uuphoria2** [comment]
ok

**Pull request closed without merging**
